#!/bin/sh

start() {
    echo "Starting luckfox_pico_rtp..."

    export LD_LIBRARY_PATH=/oem/usr/lib:$LD_LIBRARY_PATH

    /vtx/bin/luckfox_pico_rtp -i 127.0.0.1 -p 5602 -w 1920 -h 1080 -f 90 -e 1 -b 2 -g 60 &
    echo $! > /var/run/luckfox_pico_rtp.pid
}

stop() {
    echo "Stopping luckfox_pico_rtp..."

    if [ -f /var/run/luckfox_pico_rtp.pid ]; then
        kill $(cat /var/run/luckfox_pico_rtp.pid)
        rm /var/run/luckfox_pico_rtp.pid
    else
        echo "luckfox_pico_rtp is not running."
    fi
}

restart() {
    stop
    sleep 1
    start
}

case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac