#!/bin/sh

# 定义启动函数
start() {
    echo "Starting luckfox_pico_rtp..."

    export LD_LIBRARY_PATH=/oem/usr/lib:$LD_LIBRARY_PATH

    # 启动服务并获取PID
    /vtx/bin/luckfox_pico_rtp -i 127.0.0.1 -p 5602 -w 1920 -h 1080 -f 90 -e 1 -b 2 &
    echo $! > /var/run/luckfox_pico_rtp.pid  # 记录进程ID
}

stop() {
    echo "Stopping luckfox_pico_rtp..."

    if [ -f /var/run/luckfox_pico_rtp.pid ]; then
        kill $(cat /var/run/luckfox_pico_rtp.pid)
        rm /var/run/luckfox_pico_rtp.pid
    else
        echo "luckfox_pico_rtp is not running."
    fi
}

restart() {
    stop
    sleep 1
    start
}

# 处理传入的参数
case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac