#!/bin/sh

case $1 in
    start)
        echo 'eth0 set static IP: 192.168.100.10'

        ifconfig eth0 192.168.100.10 netmask 255.255.255.0
        route add default gw 192.168.100.1
    ;;
    stop)
    ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
    ;;
esac