#!/bin/sh

# 启用脚本的环境变量文件
. /etc/default/wifibroadcast
WFB_PROFILE="drone"

# 定义启动函数
start() {
    echo "Starting wifibroadcast profile ${WFB_PROFILE}..."

    airmon-ng check kill
    
    # 启动服务并获取PID
    python3 /usr/bin/wfb-server ${WFB_PROFILE} ${WFB_NICS} &
    echo $! > /var/run/wifibroadcast.pid  # 记录进程ID
}

stop() {
    echo "Stopping wifibroadcast profile ${WFB_PROFILE}..."
    
    if [ -f /var/run/wifibroadcast.pid ]; then
        kill $(cat /var/run/wifibroadcast.pid)
        rm /var/run/wifibroadcast.pid
    else
        echo "wifibroadcast is not running."
    fi
}

restart() {
    stop
    sleep 1
    start
}

# 处理传入的参数
case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac