#!/bin/sh

. /etc/default/wifibroadcast
WFB_PROFILE="drone"

start() {
    echo "Starting wifibroadcast profile ${WFB_PROFILE}..."

    airmon-ng check kill
    
    python3 /usr/bin/wfb-server ${WFB_PROFILE} ${WFB_NICS} &
    echo $! > /var/run/wifibroadcast.pid
}

stop() {
    echo "Stopping wifibroadcast profile ${WFB_PROFILE}..."
    
    if [ -f /var/run/wifibroadcast.pid ]; then
        kill $(cat /var/run/wifibroadcast.pid)
        rm /var/run/wifibroadcast.pid
    else
        echo "wifibroadcast is not running."
    fi
}

restart() {
    stop
    sleep 1
    start
}

case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac